### ISSUE TITLE
Realizar entrevistas a diferentes usuarios

### ISSUE THREAD

**Issue by GuillermoOvejeroSanchez** [DSI-ucm/Memoria-Investigacion#13]
- [x] Persona que vive sola (Lo hace pedro)
- [x] Piso compartido (la hace Davó)
- [x] Familiar que lleva la casa (Guillermo)
- [x] Familiar que no lleva la casa

**Comment by daviddavo** [comment]
Según el enunciado de la práctica es básicamente mínimo 4 participantes.

Yo creo que valdría con hacer lo siguiente:
- 1 persona que vive sola
- 2 de la familia (1 madre/padre que lleve la casa y 1 madre/padre que trabaje o lo que sea y no lleve la casa)
- 1 de piso compartido
